service: toggler


provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:DescribeStream
       Resource:
        Fn::GetAtt: [ FeatureTogglesDBTable, Arn ]
    - Effect: "Allow"
      Action:
        - ses:SendEmail
      Resource: "*"

functions:
  getToggles:
    handler: handler.getToggles
    events:
      - http:
          path: toggles
          method: get
  createToggle:
    handler: handler.createToggle
    events:
      - http:
          path: toggles
          method: post
  notifyUser:
    handler: handler.notifyNewFeature
    events:
      - stream: arn:aws:dynamodb:us-east-1:737651399098:table/FeatureToggles/stream/2019-01-31T02:10:11.056
    environment:
      SOURCE_ADDRESS: ${env:SOURCE_ADDRESS}
      TO_ADDRESS: ${env:TO_ADDRESS}

# you can add CloudFormation resource templates here
resources:
  Resources:
    FeatureTogglesDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FeatureToggles
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: "S"
        KeySchema:
          - AttributeName: name
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
